"use client";
import { useState } from "react";
import Link from "next/link";
import { usePortal } from "../components/portal-provider";
import { PortalHeader, Icon, EmptyState } from "../components/portal-ui";
import IngredientArt from "../pizzas/[slug]/ingredient-art";
import { quoteItem, isAvailable, defaultConfiguration } from "../../lib/commerce";
import { formatPrice } from "../../lib/catalog";

const steps=["Tamanho & sabores","Borda","Ingredientes","Seu toque"];
export default function PizzaBuilder({ initialFlavor }) {
  const { catalog, add }=usePortal();
  const first=catalog.pizzas.find(p=>p.id===initialFlavor&&isAvailable(p,catalog))||catalog.pizzas.find(p=>isAvailable(p,catalog));
  const [configuration,setConfiguration]=useState(()=>defaultConfiguration(first?.id||"",catalog.sizes.find(s=>s.id==="grande"&&s.active)?.id||catalog.sizes.find(s=>s.active)?.id));
  const [step,setStep]=useState(0);const [category,setCategory]=useState(first?.category||"savory");const [error,setError]=useState("");const [added,setAdded]=useState(false);
  const flavors=catalog.pizzas.filter(p=>configuration.flavorIds.includes(p.id));
  const size=catalog.sizes.find(s=>s.id===configuration.sizeId);
  const crusts=catalog.crusts.filter(c=>c.active&&(c.category==="all"||c.category===category));
  const recipeIds=[...new Set(flavors.flatMap(p=>p.ingredientIds))];
  const recipe=catalog.ingredients.filter(i=>recipeIds.includes(i.id));
  const extras=catalog.ingredients.filter(i=>i.active&&i.allowExtra&&(i.category==="all"||i.category===category));
  let quote=null;let quoteError="";try{quote=quoteItem(catalog,configuration)}catch(e){quoteError=e.message}
  function update(patch){setConfiguration(current=>({...current,...patch}));setError("");setAdded(false)}
  function chooseCategory(value){if(value===category)return;const next=catalog.pizzas.find(p=>p.category===value&&isAvailable(p,catalog));setCategory(value);update({flavorIds:next?[next.id]:[],crustId:"tradicional",extras:[],removedIngredientIds:[]})}
  function chooseFlavor(pizza){const ids=configuration.flavorIds;if(ids.includes(pizza.id)){if(ids.length===1){setError("Mantenha pelo menos um sabor na pizza.");return}update({flavorIds:ids.filter(id=>id!==pizza.id),removedIngredientIds:[],extras:[]});return}if(ids.length>=size.maxFlavors){if(size.maxFlavors===1){update({flavorIds:[pizza.id],removedIngredientIds:[],extras:[]});return}setError(`Este tamanho aceita até ${size.maxFlavors} sabores. Retire um sabor para trocar.`);return}update({flavorIds:[...ids,pizza.id],removedIngredientIds:[]})}
  function changeExtra(id,amount){const current=configuration.extras.find(i=>i.ingredientId===id);if(!current&&configuration.extras.length>=catalog.settings.maxExtras){setError(`Escolha até ${catalog.settings.maxExtras} adicionais diferentes.`);return}const quantity=(current?.quantity||0)+amount;if(quantity>3)return;update({extras:quantity<=0?configuration.extras.filter(i=>i.ingredientId!==id):current?configuration.extras.map(i=>i.ingredientId===id?{...i,quantity}:i):[...configuration.extras,{ingredientId:id,quantity}],removedIngredientIds:configuration.removedIngredientIds.filter(i=>i!==id)})}
  function addToBag(){if(!quote){setError(quoteError);return}try{add(configuration);setAdded(true)}catch(e){setError(e.message)}}
  return <div className="sp-builder-page"><PortalHeader /><main className="sp-builder-main"><Link className="sp-text-link" href="/#cardapio">← Voltar ao cardápio</Link><div className="sp-page-heading"><div><p className="eyebrow"><span /> UM BOM ENCONTRO, DO SEU JEITO</p><h1>A pizza tem a sua cara<span>.</span></h1><p>Escolha os sabores, encontre a borda perfeita e dê seu toque final.</p></div><span className="sp-builder-note"><Icon name="pizza" />Preparada para a sua combinação</span></div>
      <div className="sp-builder-layout"><aside className="sp-builder-preview"><div className="sp-preview-heading"><span>SUA COMBINAÇÃO</span><span>{size?.name}</span></div><div className="sp-builder-pizza"><div className="sp-builder-orbit" />{flavors.map((p,index)=><img key={p.id} src={p.image} alt={`${flavors.length>1?`${index+1} de ${flavors.length} sabores: `:""}${p.name}`} width="550" height="550" style={flavors.length>1?{maskImage:`conic-gradient(from -90deg, transparent 0deg ${index*360/flavors.length}deg, black ${index*360/flavors.length}deg ${(index+1)*360/flavors.length}deg, transparent ${(index+1)*360/flavors.length}deg 360deg)`,WebkitMaskImage:`conic-gradient(from -90deg, transparent 0deg ${index*360/flavors.length}deg, black ${index*360/flavors.length}deg ${(index+1)*360/flavors.length}deg, transparent ${(index+1)*360/flavors.length}deg 360deg)`}:undefined} />)}{configuration.crustId!=="tradicional"&&<span className="sp-preview-crust">Borda {crusts.find(c=>c.id===configuration.crustId)?.name}</span>}</div><div className="sp-preview-copy"><p className="eyebrow">FEITA PARA O SEU MOMENTO</p><h2>{flavors.length===1?flavors[0]?.name:flavors.length===2?"Dois sabores. Um encontro.":"Três sabores. Sua escolha."}</h2><p>{flavors.map(p=>p.name).join(" + ")}</p><div className="sp-preview-badges"><span>{size?.name}</span><span>{flavors.length} {flavors.length===1?"sabor":"sabores"}</span>{configuration.extras.length>0&&<span>{configuration.extras.length} adicionais</span>}</div></div><div className="sp-builder-price"><span>Uma pizza, do seu jeito<strong>{quote?formatPrice(quote.unitPrice):"Revise sua seleção"}</strong></span><span aria-hidden="true">↗</span></div><p className="sp-pricing-rule">{catalog.settings.halfPricing==="highest"?"Vários sabores: vale o preço do sabor de maior valor.":"Vários sabores: vale a média dos preços dos sabores."} Bordas e adicionais são somados. A imagem ilustra a combinação.</p></aside>
      <section className="sp-builder-options"><nav className="sp-builder-steps" aria-label="Etapas da personalização">{steps.map((label,index)=><button key={label} type="button" className={step===index?"is-current":step>index?"is-complete":""} aria-current={step===index?"step":undefined} onClick={()=>{setStep(index);setError("")}}><span>{step>index?<Icon name="check" size={12} />:`0${index+1}`}</span><small>{label}</small></button>)}</nav><div className="sp-builder-step-content"><span className="sp-step-label">PASSO 0{step+1} DE 04</span><h2>{step===0?"O tamanho do seu encontro.":step===1?"Um cuidado até a borda.":step===2?"Cada ingrediente, sua escolha.":"O toque final é seu."}</h2><p className="sp-form-intro">{step===0?"Uma receita favorita ou uma combinação de sabores. Comece por aqui.":step===1?"A tradicional da casa ou uma borda recheada para completar.":step===2?"Mantenha a receita da casa, retire um ingrediente ou acrescente mais sabor.":"Deixe uma observação para a cozinha e confira sua combinação."}</p>
        {step===0&&<><div className="sp-size-options">{catalog.sizes.filter(s=>s.active).map(s=><button type="button" key={s.id} aria-pressed={configuration.sizeId===s.id} className={configuration.sizeId===s.id?"is-selected":""} onClick={()=>update({sizeId:s.id,flavorIds:configuration.flavorIds.slice(0,s.maxFlavors)})}><Icon name="pizza" size={s.id==="grande"?31:24} /><span><strong>{s.name}</strong><small>{s.description}</small><em>Até {s.maxFlavors} {s.maxFlavors===1?"sabor":"sabores"}</em></span><i /></button>)}</div><div className="sp-subheading"><h3>Escolha seus sabores</h3><span>{configuration.flavorIds.length} / {size?.maxFlavors}</span></div><div className="sp-category-tabs"><button type="button" className={category==="savory"?"is-selected":""} onClick={()=>chooseCategory("savory")}>Salgadas</button><button type="button" className={category==="sweet"?"is-selected":""} onClick={()=>chooseCategory("sweet")}>Doces</button></div><div className="sp-flavor-options">{catalog.pizzas.filter(p=>p.category===category&&isAvailable(p,catalog)).map(p=><button type="button" key={p.id} aria-pressed={configuration.flavorIds.includes(p.id)} className={configuration.flavorIds.includes(p.id)?"is-selected":""} onClick={()=>chooseFlavor(p)}><img src={p.image} alt="" width="80" height="80" /><span><strong>{p.name}</strong><small>{p.description}</small><em>{formatPrice(p.prices[configuration.sizeId])}</em></span><i>{configuration.flavorIds.includes(p.id)&&<Icon name="check" size={13} />}</i></button>)}{!catalog.pizzas.some(p=>p.category===category&&isAvailable(p,catalog))&&<EmptyState title="Este sabor volta em breve." text="Escolha uma categoria disponível para continuar." />}</div></>}
        {step===1&&<div className="sp-crust-options">{crusts.map(c=><button type="button" key={c.id} aria-pressed={configuration.crustId===c.id} className={configuration.crustId===c.id?"is-selected":""} onClick={()=>update({crustId:c.id})}><span className="sp-crust-icon"><Icon name="pizza" size={28} /></span><span><strong>{c.name}</strong><small>{c.id==="tradicional"?"A massa da casa, sem recheio na borda.":`Recheio de ${c.name.toLowerCase()} na borda.`}</small></span><em>{c.prices[configuration.sizeId]===0?"Inclusa":`+ ${formatPrice(c.prices[configuration.sizeId])}`}</em><i>{configuration.crustId===c.id&&<Icon name="check" size={13} />}</i></button>)}</div>}
        {step===2&&<><div className="sp-subheading"><h3>O que já vai na receita</h3><span>Toque para retirar</span></div><div className="sp-recipe-options">{recipe.map(i=>{const removed=configuration.removedIngredientIds.includes(i.id);return <button type="button" className={removed?"is-removed":""} key={i.id} aria-pressed={!removed} onClick={()=>update({removedIngredientIds:removed?configuration.removedIngredientIds.filter(id=>id!==i.id):[...configuration.removedIngredientIds,i.id],extras:configuration.extras.filter(e=>e.ingredientId!==i.id)})}><IngredientArt name={i.name} /><span><strong>{i.name}</strong><small>{removed?"Retirado da receita":"Na receita"}</small></span><span>{removed?"+":"−"}</span></button>})}</div><p className="sp-form-help">Retirar ingredientes mantém o preço da receita. Informe restrições nas observações para a cozinha confirmar seu pedido.</p><div className="sp-subheading"><h3>Mais um pouco de sabor</h3><span>Até {catalog.settings.maxExtras} adicionais</span></div><div className="sp-extra-options">{extras.map(i=>{const quantity=configuration.extras.find(e=>e.ingredientId===i.id)?.quantity||0;return <div key={i.id}><IngredientArt name={i.name} /><span><strong>{i.name}</strong><small>+ {formatPrice(i.prices[configuration.sizeId])} / porção</small></span><div><button type="button" aria-label={`Retirar adicional de ${i.name}`} disabled={!quantity} onClick={()=>changeExtra(i.id,-1)}>−</button><span>{quantity}</span><button type="button" aria-label={`Acrescentar ${i.name}`} disabled={quantity>=3||catalog.settings.maxExtras===0} onClick={()=>changeExtra(i.id,1)}>+</button></div></div>})}</div></>}
        {step===3&&<><label className="sp-field">Observações para a cozinha<textarea rows={3} placeholder="Algo que devemos saber sobre sua pizza?" value={configuration.note} maxLength={240} onChange={e=>update({note:e.target.value})} /><small>{configuration.note.length} / 240 caracteres</small></label><div className="sp-builder-review"><h3>Sua combinação, por inteiro.</h3><dl><div><dt>Sabores</dt><dd>{flavors.map(p=>p.name).join(" + ")}</dd></div><div><dt>Tamanho</dt><dd>{size?.name}</dd></div><div><dt>Borda</dt><dd>{quote?.crust}</dd></div>{quote?.removed.length>0&&<div><dt>Retirar</dt><dd>{quote.removed.join(", ")}</dd></div>}{quote?.extras.length>0&&<div><dt>Adicionais</dt><dd>{quote.extras.map(i=>`${i.quantity}× ${i.name}`).join(", ")}</dd></div>}</dl><div className="sp-builder-cost"><span>Receita<strong>{quote&&formatPrice(quote.basePrice)}</strong></span><span>Borda<strong>{quote&&formatPrice(quote.crustPrice)}</strong></span><span>Adicionais<strong>{quote&&formatPrice(quote.extrasPrice)}</strong></span><span>Total da pizza<strong>{quote&&formatPrice(quote.unitPrice)}</strong></span></div></div></>}
        {(error||quoteError)&&<p className="sp-form-error" role="alert">{error||quoteError}</p>}{!catalog.settings.open&&<p className="sp-form-help">A casa está pausada para novos pedidos. Você pode explorar as opções.</p>}
      </div><div className="sp-builder-step-footer">{step>0?<button type="button" className="sp-secondary-button" onClick={()=>{setStep(s=>s-1);setError("")}}>← Voltar</button>:<Link className="sp-text-link" href="/#cardapio">Voltar ao cardápio</Link>}{step<3?<button className="button button-primary" type="button" disabled={!quote} onClick={()=>{setStep(s=>s+1);setError("")}}>Continuar <Icon name="arrow" size={17} /></button>:added?<Link href="/sacola" className="button button-primary">Ver minha sacola <Icon name="bag" size={17} /></Link>:<button className="button button-primary" type="button" onClick={addToBag} disabled={!quote||!catalog.settings.open}>Adicionar à sacola <Icon name="plus" size={17} /></button>}</div></section></div>
    </main></div>;
}
