"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import BrandMark from "../components/brand-mark";
import { usePortal, api } from "../components/portal-provider";
import { Icon, EmptyState, StatusPill, logout } from "../components/portal-ui";
import { formatPrice } from "../../lib/catalog";
import { isAvailable, ORDER_STATUSES } from "../../lib/commerce";
import IngredientArt from "../pizzas/[slug]/ingredient-art";

const tabs = [["overview","grid","Visão geral"],["orders","bag","Pedidos"],["pizzas","pizza","Sabores"],["ingredients","leaf","Ingredientes"],["crusts","pizza","Bordas"],["customization","settings","Personalização"],["customers","user","Clientes"],["settings","settings","A casa"]];
const clone = value => JSON.parse(JSON.stringify(value));
const blankItem = (kind) => {
  const id = `${kind === "pizzas" ? "sabor" : kind === "ingredients" ? "ingrediente" : "borda"}-${crypto.randomUUID().slice(0,8)}`;
  if (kind === "pizzas") return { id, name: "Novo sabor", description: "Descreva a sua receita.", tag: "Novidade", introduction: "", ingredientIds: [], category: "savory", active: false, image: "/images/pizzas/margherita.webp", imageAlt: "Nova pizza da casa", prices: { individual: 34, grande: 54 } };
  if (kind === "ingredients") return { id, name: "Novo ingrediente", note: "", category: "savory", active: true, allowExtra: true, prices: { individual: 3, grande: 5 }, profile: "", role: "", texture: "" };
  return { id, name: "Nova borda", category: "all", active: true, prices: { individual: 0, grande: 0 } };
};
function PriceFields({ item, update }) { return <div className="sp-price-fields">{["individual","grande"].map(size=><label className="sp-field" key={size}>{size === "individual" ? "Individual" : "Grande"} (R$)<input type="number" min="0" max="9999" step=".01" value={item.prices[size]} onChange={e=>update({prices:{...item.prices,[size]:e.target.value===""?"":Number(e.target.value)}})} required /></label>)}</div>; }
function Toggle({ label, checked, onChange, hint }) { return <label className="sp-toggle-row"><span><strong>{label}</strong>{hint&&<small>{hint}</small>}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} /><i aria-hidden="true" /></label>; }

export default function AdminWorkspace({ initialCatalog, initialOrders, adminName }) {
  const { setCatalog: publishCatalog, notify } = usePortal();
  const [catalog,setCatalog]=useState(clone(initialCatalog)); const [saved,setSaved]=useState(JSON.stringify(initialCatalog)); const [tab,setTab]=useState("overview");
  const [orders,setOrders]=useState(initialOrders); const [customers,setCustomers]=useState([]); const [selected,setSelected]=useState({pizzas:initialCatalog.pizzas[0]?.id,ingredients:initialCatalog.ingredients[0]?.id,crusts:initialCatalog.crusts[0]?.id});
  const [search,setSearch]=useState(""); const [orderFilter,setOrderFilter]=useState("all"); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [savingOrder,setSavingOrder]=useState("");
  const dirty=JSON.stringify(catalog)!==saved;
  useEffect(()=>{const timer=setInterval(()=>api("/api/admin/orders").then(data=>setOrders(data.orders)).catch(()=>{}),15000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(tab==="customers")api("/api/admin/customers").then(data=>setCustomers(data.customers)).catch(e=>setError(e.message));setSearch("");setError("")},[tab]);
  useEffect(()=>{if(!dirty)return;const handler=e=>{e.preventDefault();e.returnValue=""};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler)},[dirty]);
  function updateItem(kind,id,patch) { setCatalog(current=>({...current,[kind]:current[kind].map(item=>item.id===id?{...item,...patch}:item)}));setError(""); }
  function updateSettings(patch) { setCatalog(current=>({...current,settings:{...current.settings,...patch}}));setError(""); }
  function addItem(kind) { const item=blankItem(kind);setCatalog(current=>({...current,[kind]:[...current[kind],item]}));setSelected(current=>({...current,[kind]:item.id}));setSearch(""); }
  function removeItem(kind,id) {
    if(kind==="crusts"&&id==="tradicional"){setError("A borda tradicional é a opção padrão e deve ser mantida.");return}
    if(kind==="ingredients"&&catalog.pizzas.some(p=>p.ingredientIds.includes(id))){setError("Este ingrediente faz parte de uma receita. Retire-o dos sabores antes de removê-lo.");return}
    const item=catalog[kind].find(i=>i.id===id);if(!window.confirm(`Remover ${item.name} do cardápio? Pedidos anteriores serão preservados.`))return;
    const next=catalog[kind].filter(i=>i.id!==id);setCatalog(current=>({...current,[kind]:next}));setSelected(current=>({...current,[kind]:next[0]?.id}));
  }
  async function save() { setBusy(true);setError("");try{const next=await api("/api/admin/catalog","PUT",catalog);setCatalog(next);setSaved(JSON.stringify(next));publishCatalog(next);notify("Cardápio publicado. A loja e os novos pedidos já usam as alterações.")}catch(e){setError(e.message)}finally{setBusy(false)} }
  async function reload() { if(dirty&&!window.confirm("Recarregar e descartar as alterações ainda não salvas?"))return;try{const next=await api("/api/admin/catalog");setCatalog(next);setSaved(JSON.stringify(next));publishCatalog(next);setError("");notify("Dados atualizados.")}catch(e){setError(e.message)} }
  async function changeStatus(id,status) {setSavingOrder(id);try{const result=await api("/api/admin/orders","PATCH",{id,status});setOrders(current=>current.map(o=>o.id===id?result.order:o));notify("Status do pedido atualizado.")}catch(e){setError(e.message)}finally{setSavingOrder("")} }
  function exportCsv() { const rows=[["Pedido","Data","Status","Subtotal","Modalidade"],...orders.map(o=>[o.id,o.createdAt,o.status,o.subtotal,o.fulfillment])];const csv="\uFEFF"+rows.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(";")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="spadoni-pedidos.csv";a.click();URL.revokeObjectURL(url); }
  const recent=orders.slice(0,6);const open=orders.filter(o=>!["Concluído","Cancelado"].includes(o.status));const value=orders.filter(o=>o.status!=="Cancelado").reduce((n,o)=>n+o.total,0);
  const menuKind=["pizzas","ingredients","crusts"].includes(tab)?tab:null;const activeItem=menuKind?catalog[menuKind].find(i=>i.id===selected[menuKind]):null;
  const visibleItems=menuKind?catalog[menuKind].filter(item=>item.name.toLowerCase().includes(search.toLowerCase())):[];
  const filteredOrders=orders.filter(o=>(orderFilter==="all"||orderFilter==="open"&&!['Concluído','Cancelado'].includes(o.status)||o.status===orderFilter)&&`${o.id} ${o.customer.name} ${o.customer.phone}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="sp-admin-shell"><aside className="sp-admin-sidebar"><Link className="brand" href="/"><BrandMark /><span>SPADONI<span className="brand-period">.</span></span></Link><span className="sp-admin-caption">CENTRAL DA CASA</span><nav aria-label="Administração">{tabs.map(([id,icon,label])=><button type="button" key={id} onClick={()=>setTab(id)} className={tab===id?"is-active":""}><Icon name={icon} />{label}{id==="orders"&&open.length>0&&<span>{open.length}</span>}</button>)}</nav><div className="sp-admin-sidebar-bottom"><div><span className={`sp-store-dot${catalog.settings.open?" is-open":""}`} /><span>{catalog.settings.open?"Recebendo pedidos":"Pedidos pausados"}</span></div><Link href="/" target="_blank">Ver minha loja <Icon name="arrow" size={16} /></Link><button type="button" onClick={()=>{if(dirty&&!window.confirm("Sair sem salvar as alterações do cardápio?"))return;logout().catch(e=>setError(e.message))}}><Icon name="logout" size={17} />Sair</button></div></aside><div className="sp-admin-content"><header className="sp-admin-topbar"><span><small>SPADONI /</small> {tabs.find(t=>t[0]===tab)?.[2]}</span><div><span className="sp-admin-user"><Icon name="user" size={17} />{adminName.split(" ")[0]}</span><button className="sp-secondary-button" type="button" onClick={reload} disabled={busy}>Recarregar</button><button className="button button-primary" type="button" onClick={save} disabled={!dirty||busy}>{busy?"Salvando…":dirty?"Publicar alterações":"Tudo salvo"}<Icon name={dirty?"arrow":"check"} size={15} /></button></div></header><main className="sp-admin-main"><p className="eyebrow"><span /> O JEITO SPADONI DE CUIDAR DA CASA</p><div className="sp-page-heading"><div><h1>{tab==="overview"?<>Tudo em seu lugar<span>.</span></>:tabs.find(t=>t[0]===tab)?.[2]}</h1><p>{tab==="overview"?"Um olhar sobre a cozinha, a vitrine e os próximos bons encontros.":tab==="orders"?"Do primeiro clique à primeira fatia. Acompanhe cada pedido.":tab==="pizzas"?"Crie receitas, ajuste valores e escolha o que entra na vitrine.":tab==="ingredients"?"Cada detalhe do sabor, com disponibilidade e preço dos adicionais.":tab==="crusts"?"Um cuidado a mais na última mordida.":tab==="customization"?"Defina como seus clientes podem montar as próprias pizzas.":tab==="customers"?"Quem faz parte dos bons encontros da casa.":"Os detalhes que ajudam seus clientes a encontrar a SPADONI."}</p></div>{menuKind&&<button className="button button-primary" type="button" onClick={()=>addItem(menuKind)}><Icon name="plus" size={17} />{menuKind==="pizzas"?"Novo sabor":menuKind==="ingredients"?"Novo ingrediente":"Nova borda"}</button>}</div>
      {dirty&&<div className="sp-draft-notice"><Icon name="edit" size={16} />Há alterações no rascunho. Use “Publicar alterações” para atualizar a loja.</div>}{error&&<div className="sp-error-banner" role="alert">{error}<button type="button" onClick={()=>setError("")} aria-label="Fechar aviso">×</button></div>}
      {tab==="overview"&&<><div className="sp-admin-stats"><article><span><Icon name="bag" />Pedidos registrados</span><strong>{orders.length}</strong><small>Histórico recente da casa</small></article><article><span><Icon name="clock" />Na cozinha</span><strong>{open.length}</strong><small>Pedidos em andamento</small></article><article><span><Icon name="pizza" />Na vitrine</span><strong>{catalog.pizzas.filter(p=>isAvailable(p,catalog)).length}</strong><small>Sabores disponíveis</small></article><article><span><Icon name="grid" />Valor registrado</span><strong>{formatPrice(value)}</strong><small>Pedidos; pagamento não confirmado</small></article></div><div className="sp-admin-overview-grid"><section className="sp-surface"><div className="sp-subheading"><h2>O movimento da casa</h2><button type="button" onClick={()=>setTab("orders")}>Ver pedidos →</button></div>{recent.length?<div className="sp-recent-orders">{recent.map(o=><div key={o.id}><span><strong>{o.id}</strong><small>{o.customer.name}</small></span><StatusPill status={o.status} /><strong>{formatPrice(o.total)}</strong></div>)}</div>:<EmptyState icon="bag" title="A cozinha está tranquila." text="Os pedidos registrados pelos clientes aparecerão aqui." />}</section><section className="sp-admin-quick"><p className="eyebrow">SUA VITRINE, SEU CUIDADO</p><h2>Boas receitas<br /><em>merecem atenção.</em></h2><p>Atualize o cardápio, cuide dos ingredientes e deixe cada pedido com a cara da casa.</p><button type="button" onClick={()=>setTab("pizzas")}>Cuidar do cardápio <Icon name="arrow" size={18} /></button><img src="/images/pizzas/margherita.webp" alt="" width="260" height="260" /></section></div></>}
      {tab==="orders"&&<><div className="sp-admin-toolbar"><label className="sp-search"><Icon name="search" size={17} /><input aria-label="Buscar pedido ou cliente" placeholder="Pedido, nome ou telefone" value={search} onChange={e=>setSearch(e.target.value)} /></label><select aria-label="Filtrar pedidos" value={orderFilter} onChange={e=>setOrderFilter(e.target.value)}><option value="all">Todos os pedidos</option><option value="open">Em andamento</option>{ORDER_STATUSES.map(s=><option key={s}>{s}</option>)}</select><button className="sp-secondary-button" type="button" onClick={exportCsv}>Exportar CSV</button></div><div className="sp-admin-order-grid">{filteredOrders.length?filteredOrders.map(o=><article className="sp-surface sp-admin-order" key={o.id}><div className="sp-order-card-top"><span><strong>{o.id}</strong><small>{new Date(o.createdAt).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo",dateStyle:"short",timeStyle:"short"})}</small></span><StatusPill status={o.status} /></div><div className="sp-order-customer"><Icon name="user" size={17} /><span>{o.customer.name}<small>{o.customer.phone}</small></span><strong>{formatPrice(o.total)}</strong></div><ul>{o.items.map((i,index)=><li key={index}><strong>{i.quantity}× {i.label}</strong><span>{i.details}</span>{i.configuration.note&&<em>{i.configuration.note}</em>}</li>)}</ul><p className="sp-order-destination"><Icon name="pin" size={16} />{o.fulfillment==="pickup"?"Retirada no balcão":`${o.address.street}, ${o.address.number} · ${o.address.neighborhood} · ${o.address.city}${o.address.complement?` · ${o.address.complement}`:""}`}</p>{o.note&&<p className="sp-order-note">{o.note}</p>}<div className="sp-order-payment">Pagamento: {o.paymentStatus}{o.fulfillment==="delivery"&&<span>Frete a confirmar com o cliente</span>}</div><label className="sp-field">Atualizar andamento<select value={o.status} disabled={savingOrder===o.id||["Concluído","Cancelado"].includes(o.status)} onChange={e=>changeStatus(o.id,e.target.value)}>{ORDER_STATUSES.filter(s=>o.fulfillment==="pickup"?s!=="Saiu para entrega":s!=="Pronto para retirada").map(s=><option key={s}>{s}</option>)}</select></label></article>):<EmptyState icon="bag" title="Nenhum pedido por aqui." text="Os novos pedidos vão aparecer nesta lista." />}</div></>}
      {menuKind&&<><div className="sp-admin-toolbar"><label className="sp-search"><Icon name="search" size={17} /><input aria-label="Buscar no cardápio" placeholder={menuKind==="pizzas"?"Buscar um sabor…":"Buscar pelo nome…"} value={search} onChange={e=>setSearch(e.target.value)} /></label><span>{catalog[menuKind].length} itens no rascunho</span></div><div className="sp-catalog-editor"><div className="sp-catalog-list">{visibleItems.map(item=><button className={activeItem?.id===item.id?"is-selected":""} type="button" key={item.id} onClick={()=>setSelected(current=>({...current,[menuKind]:item.id}))}>{menuKind==="pizzas"?<img src={item.image} alt="" width="80" height="80" />:menuKind==="ingredients"?<IngredientArt name={item.name} />:<Icon name="pizza" size={31} />}<span><strong>{item.name}</strong><small>{formatPrice(item.prices.individual)} / {formatPrice(item.prices.grande)}</small></span><i className={item.active?"is-active":""} aria-label={item.active?"Ativo":"Pausado"} /></button>)}{visibleItems.length===0&&<p className="sp-form-help">Nenhum item encontrado.</p>}</div>{activeItem?<section className="sp-surface sp-item-editor"><div className="sp-editor-heading"><div><p className="eyebrow">{menuKind==="pizzas"?"A RECEITA DA CASA":menuKind==="ingredients"?"CADA DETALHE CONTA":"ATÉ A ÚLTIMA MORDIDA"}</p><h2>{activeItem.name}</h2></div><Icon name="edit" size={21} /></div><label className="sp-field">Nome<input value={activeItem.name} maxLength={80} onChange={e=>updateItem(menuKind,activeItem.id,{name:e.target.value})} /></label><label className="sp-field">Categoria<select value={activeItem.category} onChange={e=>updateItem(menuKind,activeItem.id,{category:e.target.value})}><option value="savory">Salgado</option><option value="sweet">Doce</option>{menuKind!=="pizzas"&&<option value="all">Todos os sabores</option>}</select></label>
        {menuKind==="pizzas"&&<><label className="sp-field">Descrição da receita<textarea rows={3} value={activeItem.description} maxLength={400} onChange={e=>updateItem(menuKind,activeItem.id,{description:e.target.value})} /></label><label className="sp-field">Apresentação na página do sabor<textarea rows={3} value={activeItem.introduction||""} maxLength={600} onChange={e=>updateItem(menuKind,activeItem.id,{introduction:e.target.value})} /></label><div className="sp-price-fields"><label className="sp-field">Etiqueta<input value={activeItem.tag} maxLength={40} onChange={e=>updateItem(menuKind,activeItem.id,{tag:e.target.value})} /></label><label className="sp-field">Imagem ou caminho local<input value={activeItem.image} onChange={e=>updateItem(menuKind,activeItem.id,{image:e.target.value})} /></label></div><fieldset className="sp-recipe-choices"><legend>Ingredientes da receita <small>Até 8 por sabor</small></legend>{catalog.ingredients.map(i=><label key={i.id}><input type="checkbox" checked={activeItem.ingredientIds.includes(i.id)} onChange={e=>updateItem(menuKind,activeItem.id,{ingredientIds:e.target.checked?[...activeItem.ingredientIds,i.id]:activeItem.ingredientIds.filter(id=>id!==i.id)})} /><span>{i.name}{!i.active&&<small>Indisponível</small>}</span></label>)}</fieldset></>}
        {menuKind==="ingredients"&&<><label className="sp-field">Descrição<textarea value={activeItem.note} rows={2} maxLength={240} onChange={e=>updateItem(menuKind,activeItem.id,{note:e.target.value})} /></label>{[["profile","Perfil do sabor","Ex.: FRESCO · SUAVE · AROMÁTICO"],["role","Função na receita","Ex.: O toque final"],["texture","No paladar","Ex.: Textura delicada"]].map(([key,label,placeholder])=><label className="sp-field" key={key}>{label}<input value={activeItem[key]||""} maxLength={key==="profile"?100:120} placeholder={placeholder} onChange={e=>updateItem(menuKind,activeItem.id,{[key]:e.target.value})} /></label>)}<Toggle label="Disponível como adicional" checked={activeItem.allowExtra} onChange={value=>updateItem(menuKind,activeItem.id,{allowExtra:value})} hint="O cliente pode acrescentar este ingrediente à pizza." /></>}
        <h3 className="sp-editor-subtitle">{menuKind==="pizzas"?"Preço da pizza":menuKind==="ingredients"?"Preço por porção adicional":"Valor adicional da borda"}</h3><PriceFields item={activeItem} update={patch=>updateItem(menuKind,activeItem.id,patch)} /><Toggle label="Disponível na loja" checked={activeItem.active} onChange={value=>updateItem(menuKind,activeItem.id,{active:value})} hint={menuKind==="ingredients"?"Ao pausar, receitas que usam este ingrediente ficam indisponíveis.":"Itens pausados deixam de aceitar novos pedidos."} />{menuKind==="pizzas"&&!isAvailable(activeItem,catalog)&&activeItem.active&&<p className="sp-form-error">Esta receita tem ingredientes pausados e ficará indisponível.</p>}<div className="sp-editor-footer"><Link className="sp-text-link" href={menuKind==="pizzas"?`/pizzas/${activeItem.id}`:"/montar"} target="_blank">Ver na loja ↗</Link><button type="button" onClick={()=>removeItem(menuKind,activeItem.id)} className="sp-delete-button">Remover {menuKind==="pizzas"?"sabor":menuKind==="ingredients"?"ingrediente":"borda"}</button></div></section>:<EmptyState title="Escolha um item para cuidar." text="Selecione na lista ou crie uma novidade para a casa." />}</div></>}
      {tab==="customization"&&<div className="sp-settings-grid"><section className="sp-surface"><h2>O tamanho do encontro</h2><p className="sp-form-intro">Defina os nomes dos tamanhos e quantos sabores podem ser combinados.</p>{catalog.sizes.map(size=><div className="sp-size-editor" key={size.id}><label className="sp-field">Nome do tamanho<input value={size.name} maxLength={80} onChange={e=>updateItem("sizes",size.id,{name:e.target.value})} /></label><label className="sp-field">Descrição<input value={size.description} maxLength={120} onChange={e=>updateItem("sizes",size.id,{description:e.target.value})} /></label><label className="sp-field">Máximo de sabores<select value={size.maxFlavors} onChange={e=>updateItem("sizes",size.id,{maxFlavors:Number(e.target.value)})}>{[1,2,3].map(n=><option key={n} value={n}>{n} {n===1?"sabor":"sabores"}</option>)}</select></label><Toggle label="Tamanho disponível" checked={size.active} onChange={value=>updateItem("sizes",size.id,{active:value})} /></div>)}</section><section className="sp-surface"><h2>Um preço que faz sentido</h2><p className="sp-form-intro">A regra aparece para o cliente e é aplicada no servidor, em todos os pedidos.</p><label className="sp-field">Preço para pizzas com vários sabores<select value={catalog.settings.halfPricing} onChange={e=>updateSettings({halfPricing:e.target.value})}><option value="highest">Cobrar pelo sabor de maior valor</option><option value="average">Cobrar a média dos sabores</option></select></label><div className="sp-price-example"><span>EXEMPLO · DOIS SABORES</span><p>Sabores de R$ 50 e R$ 60</p><strong>{catalog.settings.halfPricing==="highest"?"R$ 60,00":"R$ 55,00"}</strong><small>Mais o valor da borda e dos adicionais escolhidos.</small></div><label className="sp-field">Máximo de adicionais diferentes<input type="number" min="0" max="8" value={catalog.settings.maxExtras} onChange={e=>updateSettings({maxExtras:Number(e.target.value)})} /></label><p className="sp-form-help">Cada adicional pode ter até 3 porções. A remoção de ingredientes mantém o preço da receita.</p></section></div>}
      {tab==="customers"&&<><label className="sp-search"><Icon name="search" size={17} /><input aria-label="Buscar cliente" placeholder="Buscar cliente pelo nome ou e-mail" value={search} onChange={e=>setSearch(e.target.value)} /></label><div className="sp-customer-table"><table><thead><tr><th>Cliente</th><th>Contato</th><th>Pedidos</th><th>Na casa desde</th></tr></thead><tbody>{customers.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(search.toLowerCase())).map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.email}</small></td><td>{c.phone||"—"}</td><td>{c.orderCount}</td><td>{new Date(c.createdAt).toLocaleDateString("pt-BR",{timeZone:"America/Sao_Paulo"})}</td></tr>)}</tbody></table>{!customers.length&&<EmptyState icon="user" title="A mesa ainda está sendo preparada." text="Os clientes cadastrados vão aparecer aqui." />}</div></>}
      {tab==="settings"&&<div className="sp-settings-grid"><section className="sp-surface"><h2>Onde os encontros acontecem</h2><label className="sp-field">Endereço para retirada<input value={catalog.settings.storeAddress} onChange={e=>updateSettings({storeAddress:e.target.value})} maxLength={240} /></label><label className="sp-field">Horário de atendimento<input value={catalog.settings.openingHours} onChange={e=>updateSettings({openingHours:e.target.value})} maxLength={180} /></label><label className="sp-field">WhatsApp (país + DDD + número)<input type="tel" value={catalog.settings.whatsappNumber} onChange={e=>updateSettings({whatsappNumber:e.target.value.replace(/\D/g,"")})} maxLength={15} /></label><label className="sp-field">Estimativa de preparo (minutos)<input type="number" min="10" max="180" value={catalog.settings.prepMinutes} onChange={e=>updateSettings({prepMinutes:Number(e.target.value)})} /></label></section><section className="sp-surface"><h2>O ritmo da casa</h2><Toggle label="Aceitar novos pedidos" checked={catalog.settings.open} onChange={value=>updateSettings({open:value})} hint="Pause o atendimento quando a cozinha precisar." /><Toggle label="Retirada no balcão" checked={catalog.settings.pickupEnabled} onChange={value=>updateSettings({pickupEnabled:value})} /><Toggle label="Entrega" checked={catalog.settings.deliveryEnabled} onChange={value=>updateSettings({deliveryEnabled:value})} hint="Cobertura e frete são confirmados pelo WhatsApp." /><label className="sp-field">Pedido mínimo (R$)<input type="number" min="0" max="9999" step=".01" value={catalog.settings.minOrder} onChange={e=>updateSettings({minOrder:e.target.value===""?"":Number(e.target.value)})} /></label><p className="sp-form-help">A configuração de pagamento continua no servidor. Nenhuma credencial de pagamento é exibida no painel.</p></section></div>}
    </main><footer className="sp-admin-footer">SPADONI · Feita com tempo. Cuidada com carinho.</footer></div></div>;
}
