"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { PortalHeader, Icon, StatusPill } from "../../components/portal-ui";
import { usePortal, api } from "../../components/portal-provider";
import { formatPrice } from "../../../lib/catalog";

export default function OrderTracker({ initialOrder, whatsappUrl }) {
  const [order,setOrder]=useState(initialOrder);const {catalog,addMany,notify}=usePortal();const router=useRouter();
  useEffect(()=>{const timer=setInterval(()=>api(`/api/orders/${order.id}`).then(r=>setOrder(r.order)).catch(()=>{}),15000);return()=>clearInterval(timer)},[order.id]);
  const stages=["Recebido","Confirmado","Em preparo",order.fulfillment==="pickup"?"Pronto para retirada":"Saiu para entrega","Concluído"];
  const current=stages.indexOf(order.status);
  function reorder(){try{addMany(order.items.map(i=>({configuration:i.configuration,quantity:i.quantity})));router.push("/sacola")}catch(e){notify(`Revise o pedido: ${e.message}`)}}
  return <div className="sp-tracking-page"><PortalHeader /><main className="sp-tracking-main"><Link className="sp-text-link" href="/conta">← Minha conta</Link><div className="sp-page-heading"><div><p className="eyebrow"><span /> A GENTE CUIDA DE CADA FATIA</p><h1>Seu pedido está aqui<span>.</span></h1><p>{order.id} · {new Date(order.createdAt).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo",dateStyle:"medium",timeStyle:"short"})}</p></div><StatusPill status={order.status} /></div>{order.status!=="Cancelado"&&<div className="sp-timeline">{stages.map((status,index)=><div key={status} className={index<=current?"is-reached":""}><span>{index<current?<Icon name="check" size={16} />:`0${index+1}`}</span><strong>{status}</strong></div>)}</div>}<div className="sp-tracking-layout"><section className="sp-surface"><h2>Sua combinação, por inteiro.</h2><div className="sp-tracking-items">{order.items.map((item,index)=><article key={index}><img src={item.image} alt="" width="80" height="80" /><div><h3>{item.quantity}× {item.label}</h3><p>{item.details}</p>{item.configuration.note&&<small>{item.configuration.note}</small>}</div><strong>{formatPrice(item.unitPrice*item.quantity)}</strong></article>)}</div><div className="sp-tracking-total"><span>Subtotal das pizzas</span><strong>{formatPrice(order.subtotal)}</strong></div><p className="sp-form-help">Pagamento: {order.paymentStatus}.{order.fulfillment==="delivery"&&" O frete será confirmado pela equipe."}</p><button type="button" className="sp-secondary-button" onClick={reorder}>Pedir essa combinação de novo <Icon name="arrow" size={15} /></button></section><aside className="sp-tracking-aside"><section className="sp-tracking-contact"><Icon name="pizza" size={30} /><h2>Um último passo,<br /><em>um bom encontro.</em></h2><p>Seu pedido foi registrado. Confirme os detalhes e o pagamento com a nossa equipe pelo WhatsApp.</p>{whatsappUrl ? <><a className="button button-primary sp-full-button" href={whatsappUrl} target="_blank" rel="noreferrer">Confirmar pelo WhatsApp <Icon name="arrow" size={17} /></a><small>A mensagem já leva sua combinação e o número do pedido.</small></> : <p>O contato da equipe está indisponível no momento.</p>}</section><section className="sp-surface"><h2>{order.fulfillment==="pickup"?"Nos vemos na casa.":"O endereço do encontro."}</h2><p className="sp-order-destination"><Icon name="pin" size={17} />{order.address?`${order.address.street}, ${order.address.number} · ${order.address.neighborhood}, ${order.address.city}${order.address.complement?` · ${order.address.complement}`:""}`:catalog.settings.storeAddress}</p><p className="sp-form-help">{order.customer.name} · {order.customer.phone}</p>{order.note&&<p className="sp-order-note">{order.note}</p>}</section></aside></div></main></div>;
}
