"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { usePortal, api } from "../components/portal-provider";
import { PortalHeader, Icon, OrderCard, EmptyState, FavoriteButton, AddressFields, logout } from "../components/portal-ui";

const tabs = [["overview","grid","Meu cantinho"],["orders","bag","Meus pedidos"],["favorites","heart","Favoritos"],["profile","user","Meus dados"],["address","pin","Endereço"],["password","settings","Minha senha"]];
export default function CustomerDashboard({ initialOrders }) {
  const { user, setUser, catalog, notify } = usePortal(); const [tab,setTab] = useState("overview"); const [orders,setOrders] = useState(initialOrders); const [busy,setBusy] = useState(false);
  const [profile,setProfile] = useState({name:user?.name||"",phone:user?.phone||""}); const [address,setAddress] = useState(user?.address||{});
  const [password,setPassword] = useState({currentPassword:"",password:""});
  useEffect(()=>{const timer=setInterval(()=>api("/api/orders").then(data=>setOrders(data.orders)).catch(()=>{}),20000);return()=>clearInterval(timer)},[]);
  async function save(event, action) { event.preventDefault();setBusy(true);try{const body=action==="password"?{action,...password}:{action:"profile",...profile,address};const result=await api("/api/account","PATCH",body);if(result.user)setUser(result.user);if(action==="password")setPassword({currentPassword:"",password:""});notify(action==="password"?"Senha atualizada. Outras sessões foram encerradas.":"Seus dados foram salvos.")}catch(e){notify(e.message)}finally{setBusy(false)} }
  const favorites=catalog.pizzas.filter(p=>user?.favorites?.includes(p.id));
  const activeOrders=orders.filter(o=>!["Concluído","Cancelado"].includes(o.status));
  return <div className="sp-portal-page"><PortalHeader /><div className="sp-account-layout"><aside className="sp-account-sidebar"><div className="sp-user-card"><span>{(user?.name||"S").slice(0,1).toUpperCase()}</span><strong>{user?.name}</strong><small>Bom ter você por aqui.</small></div><nav aria-label="Área do cliente">{tabs.map(([id,icon,label])=><button type="button" key={id} className={tab===id?"is-active":""} onClick={()=>setTab(id)}><Icon name={icon} />{label}</button>)}</nav>{user?.role==="admin"&&<Link className="sp-admin-access" href="/admin"><Icon name="settings" />Painel administrativo ↗</Link>}<button className="sp-logout" type="button" onClick={()=>logout().catch(e=>notify(e.message))}><Icon name="logout" />Sair da conta</button><div className="sp-sidebar-note"><Icon name="pizza" size={30} /><p>Seu próximo bom encontro<br />começa com uma pizza.</p><Link href="/montar">Montar minha pizza →</Link></div></aside><main className="sp-account-main"><p className="eyebrow"><span /> SEU CANTINHO NA SPADONI</p><div className="sp-page-heading"><div><h1>{tab==="overview"?<>Olá, {user?.name?.split(" ")[0]}<span>.</span></>:tabs.find(t=>t[0]===tab)?.[2]} </h1><p>{tab==="overview"?"Favoritos à mão. Bons encontros pela frente.":tab==="orders"?"Acompanhe o que está saindo da nossa cozinha.":tab==="favorites"?"A gente guarda os sabores que conquistaram você.":"Os detalhes que deixam o próximo pedido mais fácil."}</p></div>{tab==="overview"&&<Link className="button button-primary" href="/montar">Montar uma pizza <Icon name="plus" size={17} /></Link>}</div>
      {tab==="overview"&&<><div className="sp-account-stats"><article><Icon name="bag" /><strong>{orders.length}</strong><span>bons encontros</span></article><article><Icon name="clock" /><strong>{activeOrders.length}</strong><span>pedidos em andamento</span></article><article><Icon name="heart" /><strong>{favorites.length}</strong><span>sabores favoritos</span></article></div><div className="sp-account-promo"><div><p className="eyebrow">DO SEU JEITO, ATÉ A ÚLTIMA FATIA</p><h2>Um sabor? Dois?<br /><em>Você escolhe.</em></h2><p>Combine sabores, escolha sua borda e dê o seu toque.</p><Link href="/montar">Criar minha combinação <Icon name="arrow" size={18} /></Link></div><img src="/images/pizzas/calabresa.webp" alt="Pizza de calabresa" width="300" height="300" /></div><div className="sp-subheading"><h2>Seu último pedido</h2><button type="button" onClick={()=>setTab("orders")}>Ver todos →</button></div>{orders.length?<OrderCard order={orders[0]} />:<EmptyState title="Seu primeiro encontro está por vir." text="Escolha um sabor e deixe o resto com a nossa cozinha." href="/montar" action="Montar minha pizza" />}</>}
      {tab==="orders"&&<div className="sp-orders-grid">{orders.length?orders.map(o=><OrderCard key={o.id} order={o} />):<EmptyState icon="bag" title="Sua história começa com uma fatia." text="Os pedidos feitos pela sua conta aparecerão aqui." href="/montar" />}</div>}
      {tab==="favorites"&&<div className="sp-favorites-grid">{favorites.length?favorites.map(p=><article className="sp-favorite-card" key={p.id}><div><img src={p.image} alt={p.name} width="240" height="240" /><FavoriteButton pizzaId={p.id} /></div><h3>{p.name}</h3><p>{p.description}</p><Link href={`/montar?sabor=${p.id}`} className="sp-text-link">Pedir do meu jeito <Icon name="arrow" size={16} /></Link></article>):<EmptyState icon="heart" title="Tem um sabor com a sua cara." text="Toque no coração de uma pizza para guardá-la aqui." href="/#cardapio" />}</div>}
      {(tab==="profile"||tab==="address")&&<form className="sp-profile-form sp-surface" onSubmit={e=>save(e,"profile")}><h2>{tab==="profile"?"Vamos manter contato.":"Onde a pizza encontra você."}</h2>{tab==="profile"?<><label className="sp-field">Seu nome<input autoComplete="name" value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} required maxLength={80} /></label><label className="sp-field">E-mail<input type="email" value={user?.email||""} readOnly /></label><label className="sp-field">Telefone com DDD<input type="tel" autoComplete="tel" value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})} maxLength={25} /></label></>:<AddressFields value={address} onChange={setAddress} />}<button className="button button-primary" disabled={busy}>{busy?"Salvando…":"Salvar meus dados"}<Icon name="check" size={17} /></button></form>}
      {tab==="password"&&<form className="sp-profile-form sp-surface" onSubmit={e=>save(e,"password")}><h2>Um cuidado com a sua conta.</h2><label className="sp-field">Senha atual<input type="password" autoComplete="current-password" required value={password.currentPassword} onChange={e=>setPassword({...password,currentPassword:e.target.value})} maxLength={128} /></label><label className="sp-field">Nova senha<input type="password" autoComplete="new-password" required minLength={15} maxLength={128} value={password.password} onChange={e=>setPassword({...password,password:e.target.value})} /></label><p className="sp-form-help">Use uma frase com pelo menos 15 caracteres. Ao salvar, outras sessões da sua conta serão encerradas.</p><button className="button button-primary" disabled={busy}>{busy?"Salvando…":"Atualizar minha senha"}</button></form>}
    </main></div></div>;
}
